#!/usr/bin/env ruby
git_bundles = [ 
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/ervandew/supertab.git",
  "git://github.com/vim-scripts/tComment.git",
  "git://github.com/tpope/vim-fugitive",
  "git://github.com/slack/vim-l9.git",
  "git://github.com/msanders/cocoa.vim.git",
  "git://github.com/cakebaker/scss-syntax.vim.git",
  "git://github.com/sjl/gundo.vim.git",
  "git://github.com/Rip-Rip/clang_complete",
  "git://github.com/majutsushi/tagbar.git",
  "git://github.com/Lokaltog/vim-powerline.git",
  "git://github.com/juvenn/mustache.vim.git",
  "git://github.com/groenewege/vim-less.git",
  "git://github.com/jnwhiteh/vim-golang",
  "git://github.com/nono/vim-handlebars",
  "git://github.com/tpope/vim-markdown.git",
]

vim_org_scripts = [
  #["IndexedSearch", "7062",  "plugin"],
  #["gist",          "12732", "plugin"],
  #["jquery",        "12107", "syntax"],
#  ["acp", 			"1879",  "plugin"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} --recursive #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
